// src/tasks.js
const tasks = [
  {
    id: 1,
    area: "General",
    logoUrl: "./assets/Globe-icon.webp",
    name: "Task 1",
    description: "Description 1",
    requirements: "Requirement 1",
    points: 10,
    completion: 50,
    completed: false,
  },
  {
    id: 2,
    area: "Misthalin",
    logoUrl: "./assets/Misthalin_Area_Badge.webp",
    name: "Task 2",
    description: "Description 2",
    requirements: "Requirement 2",
    points: 40,
    completion: 75,
    completed: false,
  },
  {
    id: 3,
    area: "Karamja",
    logoUrl: "./assets/Karamja_Area_Badge.webp",
    name: "Task 3",
    description: "Description 3",
    requirements: "Requirement 3",
    points: 80,
    completion: 60,
    completed: false,
  },
  {
    id: 4,
    area: "Asgarnia",
    logoUrl: "./assets/Asgarnia_Area_Badge.webp",
    name: "Task 4",
    description: "Description 4",
    requirements: "Requirement 4",
    points: 40,
    completion: 80,
    completed: false,
  },
  {
    id: 5,
    area: "Kharidian Desert",
    logoUrl: "./assets/Desert_Area_Badge.webp",
    name: "Task 5",
    description: "Description 5",
    requirements: "Requirement 5",
    points: 200,
    completion: 90,
    completed: false,
  },
  {
    id: 6,
    area: "Fremennik Provinces",
    logoUrl: "./assets/Fremennik_Area_Badge.webp",
    name: "Task 6",
    description: "Description 6",
    requirements: "Requirement 6",
    points: 40,
    completion: 70,
    completed: false,
  },
  {
    id: 7,
    area: "Kandarin",
    logoUrl: "./assets/Kandarin_Area_Badge.webp",
    name: "Task 7",
    description: "Description 7",
    requirements: "Requirement 7",
    points: 40,
    completion: 85,
    completed: false,
  },
  {
    id: 8,
    area: "Morytania",
    logoUrl: "./assets/Morytania_Area_Badge.webp",
    name: "Task 8",
    description: "Description 8",
    requirements: "Requirement 8",
    points: 400,
    completion: 95,
    completed: false,
  },
  {
    id: 9,
    area: "Tirannwn",
    logoUrl: "./assets/Tirannwn_Area_Badge.webp",
    name: "Task 9",
    description: "Description 9",
    requirements: "Requirement 9",
    points: 10,
    completion: 100,
    completed: false,
  },
  {
    id: 10,
    area: "Wilderness",
    logoUrl: "./assets/Wilderness_Area_Badge.webp",
    name: "Task 10",
    description: "Description 10",
    requirements: "Requirement 10",
    points: 10,
    completion: 50,
    completed: false,
  },
  {
    id: 11,
    area: "Kourend",
    logoUrl: "./assets/Kourend_Area_Badge.webp",
    name: "Task 11",
    description: "Description 11",
    requirements: "Requirement 11",
    points: 10,
    completion: 75,
    completed: false,
  },
  // Add more tasks as needed
];

export default tasks;
